env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - plugin:@typescript-eslint/recommended
  - '@nuxtjs/eslint-config-typescript'
  - '@vue/prettier'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns: '**/api/**'
plugins:
  - vue
  - '@typescript-eslint'
  - vitest
rules:
  'vue/multi-word-component-names': 0
  'vue/no-multiple-template-root': 'off'
  'no-new': 'off'
  'no-console': ['error', { allow: ['warn', 'error'] }]
